### ISSUE TITLE
Add support for multiple independent folders

### ISSUE THREAD

**Issue by nohawk** [sagold/FuzzyFilePath#13]
On line 89 of "FuzzyFilePath/project/ProjectManager.py", it says "multiple independent folders are not yet supported, which results in ignored folders"... I would like to see this functionality added.

It would also be nice if I could set the "project_directory" and "base_directory" for each of these independent folders separately.

**Comment by sagold** [comment]
Hi nohawk.

I see two cases.

- subfolders added to root via project settings.folders and
- basic subfolders which could be declared as separate projects

Which is your use case?

Since a few commits i am working towards this feature, but it might get a little tricky. Meaning, this will take a while and more details would be helpful.

Thank you.

**Comment by nohawk** [comment]
Hi sagold,

I think it may be easiest to give you an example of how things are setup at my job. We develop landing pages for products and then email campaigns for those projects, etc. However the files for the sites and the emails are not created in the same directory... 

For example:
/Volumes/web/sites/product1
/Volumes/web/emails/product1

Logically it makes sense to group these together into one project and it would be nice if I could set the behavior for the file path for each folder. For instance, within sites the base_directory might be "assets/images" and in the emails it might be "images".

I hope that helps.

Thanks

**Comment by sagold** [comment]
Hi nohawk.

This helps. Thank you for the details. I will look into this feature on September.

Cheers.

**Comment by sagold** [comment]
With release v0.3.0 multiple folders are now supported
