### ISSUE TITLE
Insert Just file name

### ISSUE THREAD

**Issue by abhimanyusharma003** [sagold/FuzzyFilePath#14]
Is there any way to insert just the file name and not the full path ?

Thanks

**Comment by sagold** [comment]
Yes there ist some way:
For a trigger in settings you may add a field ['replace on insert'][https://github.com/sagold/FuzzyFilePath/wiki/Settings#replace_on_insertarray]. Here you can specify an array of regexes to be performed on the inserted filepath. In order to strip folders of a path you can add something like"^.*\\/([^\\/]*)$",
