### ISSUE TITLE
node_modules is not being ignored

### ISSUE THREAD

**Issue by joadr** [sagold/FuzzyFilePath#35]
I've tried changing the settings to the previous way, but doesn't work either?.

Also, I've set my sublime to ignore the node_modules folder also, should this extension look at "folder_exclude_patterns" in sublime's settings?

**Comment by sagold** [comment]
Hi joadr.

I will revert the ignore pattern to the previous one on the next update. The old setting is still working, but you have to restart sublime to load it correctly. And note that this is a regular expression. Some characters may have to be escaped in order to be valid.

As for using ignore folder patterns. I thought about this and would prefer to use this setting. Unfortunately sublime's settings do not support regex patterns. In my case, i am whitelisting specific node_modules, which is only possible through regex or tedious work. Another reason is, they describe different files. Sublime suggest files i want to edit, ffp suggest files i want to include. Those sets may not always be the same.

Hope this makes sense. Happy to hear other opinions.

**Comment by saschagehlich** [comment]
Any update on this one @sagold? This is a big show stopper for this plugin - it's caching >40k files in a medium sized project

**Comment by joadr** [comment]
I tried the solution provided by @sagold but didn't work for me... it's still showing the node_modules files:(

**Comment by sagold** [comment]
I am using the following _working_ configuration in my FuzzyFilePath-User-Settings:

```json
"exclude_folders": ["node\\_modules\/(?!sz).*", "bower\\_components/.*/bower\\_components"],
```

I am planing to change the default and update FFP in the next week. Please let me know if your `exclude_folders`-settings are not applied.

Regards.
sagold

**Comment by sagold** [comment]
Since version `v0.3.1` node_modules are completly ignored by default: 1bf8fd8b8ec7fb5367a1637d2312c05741eaa203
