### ISSUE TITLE
Breaks snippet

### ISSUE THREAD

**Issue by unformatt** [sagold/FuzzyFilePath#40]
Not sure if it's because my snippet has quotes in it or because it uses multiple cursors

Snippet:
```xml
<snippet>
	<content><![CDATA[console.log("${1}:", ${1});]]></content>
	<!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
	<tabTrigger>cl</tabTrigger>
	<!-- Optional: Set a scope to limit where the snippet will trigger -->
	<scope>source.js</scope>
</snippet>
```

How the snippets works normally:
![image](http://g.recordit.co/AjubOUlOZ9.gif)

How the snippets works with FFP enabled:

![image](http://g.recordit.co/u2Yw5hpiK7.gif)

**Comment by sagold** [comment]
Hi unformatt.

I tested the snippet on my machine and it works as expected. Both cursors are within the brackets. 

FuzzyFilePath does move the cursor after a completion, but only if a trigger validates on the context. I guess a trigger is active on your snippet-statement, which might probably be an issue through misconfiguration.

There is a [regex in settings](url), which triggers the jump: `"post_insert_move_characters": "^[\"\'\);]*"`. The movement may be deactivated by adding the following to your user-settings: `"post_insert_move_characters": false`

In order to debug your context adding a keybinding to the `show context command`
```
{ "keys": ["alt+y"], "command": "ffp_show_context" }
```
might help (Scroll the view to check for the Trigger-Title).

**Comment by unformatt** [comment]
`"post_insert_move_characters": false` worked - thank you
